name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened #This workflow will execute whenever a new issue is open for GitHub Repository.
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label  #Extract title of the issue and store it in a temporary variable.
        run: |
          issue_title="${{ github.event.issue.title }}" 
          if [[ "$issue_title" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi